go_binary(
    name = "0_readfile",
    srcs = ["0_readfile.go"],
)

go_binary(
    name = "1_delimiter",
    srcs = ["1_delimiter.go"],
)

go_binary(
    name = "2_strconv",
    srcs = ["2_strconv.go"],
)

go_binary(
    name = "3_calcMean",
    srcs = ["3_calcMean.go"],
)

go_binary(
    name = "4_calcMedian",
    srcs = ["4_calcMedian.go"],
)

go_binary(
    name = "5_getOnline",
    srcs = ["5_getOnline.go"],
)

go_binary(
    name = "solution",
    srcs = ["solution.go"],
)
