application: twitmock-1012
version: 1
runtime: go
api_version: go1

handlers:
- url: /form/.*
  script: _go_app
  secure: always
- url: /.*
  script: _go_app

# order matters



#/*
#All material is licensed under the Apache License Version 2.0, January 2004
#http://www.apache.org/licenses/LICENSE-2.0
#*/