go_binary(
    name = "0_readImage",
    srcs = ["0_readImage.go"],
)

go_binary(
    name = "1_decodeImage",
    srcs = ["1_decodeImage.go"],
)

go_binary(
    name = "2_abstract_1",
    srcs = ["2_abstract_1.go"],
)

go_binary(
    name = "3_decodeSeveralImages",
    srcs = ["3_decodeSeveralImages.go"],
)

go_binary(
    name = "4_abstract_3",
    srcs = ["4_abstract_3.go"],
)

go_binary(
    name = "5_pixels",
    srcs = ["5_pixels.go"],
)

go_binary(
    name = "6_addTimimg",
    srcs = ["6_addTimimg.go"],
)

go_binary(
    name = "7_abstract_6",
    srcs = ["7_abstract_6.go"],
)

go_binary(
    name = "8_concurWG",
    srcs = ["8_concurWG.go"],
)

go_binary(
    name = "9_structAndChannel",
    srcs = ["9_structAndChannel.go"],
)
