go_binary(
    name = "atoi",
    srcs = ["atoi.go"],
)

go_binary(
    name = "fizz",
    srcs = ["fizz.go"],
)

go_binary(
    name = "minmax",
    srcs = ["minmax.go"],
)

go_binary(
    name = "packagesIoOs",
    srcs = ["packagesIoOs.go"],
)

go_binary(
    name = "packagesNetHTTP",
    srcs = ["packagesNetHTTP.go"],
)

go_binary(
    name = "packagesSortStrings",
    srcs = ["packagesSortStrings.go"],
)

go_binary(
    name = "packagesStrconv",
    srcs = ["packagesStrconv.go"],
)

go_binary(
    name = "packagesTime",
    srcs = ["packagesTime.go"],
)

go_binary(
    name = "parentheses",
    srcs = ["parentheses.go"],
)

go_binary(
    name = "perfDataRace",
    srcs = ["perfDataRace.go"],
)

go_binary(
    name = "play1",
    srcs = ["play1.go"],
)

go_binary(
    name = "play2",
    srcs = ["play2.go"],
)

go_binary(
    name = "prime",
    srcs = ["prime.go"],
)

go_binary(
    name = "reader",
    srcs = ["reader.go"],
)

go_binary(
    name = "roman2integer",
    srcs = ["roman2integer.go"],
)

go_binary(
    name = "roman2integer_2",
    srcs = ["roman2integer_2.go"],
)

go_binary(
    name = "AdminCider",
    srcs = ["AdminCider.go"],
)

go_binary(
    name = "Args",
    srcs = ["Args.go"],
)

go_binary(
    name = "ArraysBasic",
    srcs = ["ArraysBasic.go"],
)

go_binary(
    name = "ArraysOps",
    srcs = ["ArraysOps.go"],
)

go_binary(
    name = "InterfacesExercise5",
    srcs = ["InterfacesExercise5.go"],
)

go_binary(
    name = "Pointers1",
    srcs = ["Pointers1.go"],
)

go_binary(
    name = "Pointers2",
    srcs = ["Pointers2.go"],
)

go_binary(
    name = "ArraysExercise1-5",
    srcs = ["ArraysExercise1-5.go"],
)

go_binary(
    name = "ArraysExercise6-8",
    srcs = ["ArraysExercise6-8.go"],
)

go_binary(
    name = "ConcurChannels1",
    srcs = ["ConcurChannels1.go"],
)

go_binary(
    name = "ConcurChannels2",
    srcs = ["ConcurChannels2.go"],
)

go_binary(
    name = "ConcurChannelsSelect",
    srcs = ["ConcurChannelsSelect.go"],
)

go_binary(
    name = "ConcurWaitGroups",
    srcs = ["ConcurWaitGroups.go"],
)

go_binary(
    name = "Types1",
    srcs = ["Types1.go"],
)

go_binary(
    name = "Types2",
    srcs = ["Types2.go"],
)

go_binary(
    name = "FunctionsBasic",
    srcs = ["FunctionsBasic.go"],
)

go_binary(
    name = "FunctionsExercise1-4",
    srcs = ["FunctionsExercise1-4.go"],
)

go_binary(
    name = "FunctionsExercise5-6",
    srcs = ["FunctionsExercise5-6.go"],
)

go_binary(
    name = "FunctionsNamedReturn",
    srcs = ["FunctionsNamedReturn.go"],
)

go_binary(
    name = "FunctionsExercise7-8",
    srcs = ["FunctionsExercise7-8.go"],
)

go_binary(
    name = "InterfacesExercise2",
    srcs = ["InterfacesExercise2.go"],
)

go_binary(
    name = "InterfacesExercise3",
    srcs = ["InterfacesExercise3.go"],
)

go_binary(
    name = "InterfacesExercise4",
    srcs = ["InterfacesExercise4.go"],
)

go_binary(
    name = "StdLibArgs1",
    srcs = ["StdLibArgs1.go"],
)

go_binary(
    name = "Structs1",
    srcs = ["Structs1.go"],
)

go_binary(
    name = "Structs2",
    srcs = ["Structs2.go"],
)

go_binary(
    name = "ArraysDyn",
    srcs = ["ArraysDyn.go"],
)

go_binary(
    name = "FlowControl1",
    srcs = ["FlowControl1.go"],
)

go_binary(
    name = "LinkedList",
    srcs = ["LinkedList.go"],
)

go_binary(
    name = "StdLibArgs2",
    srcs = ["StdLibArgs2.go"],
)

go_binary(
    name = "StdLibArtEnv",
    srcs = ["StdLibArtEnv.go"],
)

go_binary(
    name = "StdLibArtEnv_ignore",
    srcs = ["StdLibArtEnv_ignore.go"],
)

go_binary(
    name = "StdLibArtEnv_simple",
    srcs = ["StdLibArtEnv_simple.go"],
)

go_binary(
    name = "StdLibPathBasic",
    srcs = ["StdLibPathBasic.go"],
)

go_binary(
    name = "StdLibPathWalkExtensions",
    srcs = ["StdLibPathWalkExtensions.go"],
)

go_binary(
    name = "StdLibPathWalkGlob",
    srcs = ["StdLibPathWalkGlob.go"],
)

go_binary(
    name = "StdLibPathWalkMyfind",
    srcs = ["StdLibPathWalkMyfind.go"],
)

go_binary(
    name = "Structs3",
    srcs = ["Structs3.go"],
)

go_binary(
    name = "Structs4",
    srcs = ["Structs4.go"],
)

go_binary(
    name = "StructsPointer",
    srcs = ["StructsPointer.go"],
)

go_binary(
    name = "RecurFact",
    srcs = ["RecurFact.go"],
)

go_binary(
    name = "RecurFib",
    srcs = ["RecurFib.go"],
)

go_binary(
    name = "RecurFibMemoiz",
    srcs = ["RecurFibMemoiz.go"],
)

go_binary(
    name = "Reverse1",
    srcs = ["Reverse1.go"],
)

go_binary(
    name = "Reverse2",
    srcs = ["Reverse2.go"],
)

go_binary(
    name = "Reverse3",
    srcs = ["Reverse3.go"],
)

go_binary(
    name = "InterfacesExerciseSMIFO",
    srcs = ["InterfacesExerciseSMIFO.go"],
)

go_binary(
    name = "InterfacesExerciseSMIO",
    srcs = ["InterfacesExerciseSMIO.go"],
)
