go_binary(
    name = "concurBasic",
    srcs = ["concurBasic.go"],
)

go_binary(
    name = "concurChannels",
    srcs = ["concurChannels.go"],
)

go_binary(
    name = "concurChannelsBuffered",
    srcs = ["concurChannelsBuffered.go"],
)

go_binary(
    name = "concurShip",
    srcs = ["concurShip.go"],
)

go_binary(
    name = "slowCounter",
    srcs = ["slowCounter.go"],
)

go_binary(
    name = "tickCounter",
    srcs = ["tickCounter.go"],
)

go_binary(
    name = "1_mutexMutex",
    srcs = ["1_mutexMutex.go"],
)

go_binary(
    name = "1_mutexRWMutex",
    srcs = ["1_mutexRWMutex.go"],
)

go_binary(
    name = "2_waitGroup",
    srcs = ["2_waitGroup.go"],
)

go_binary(
    name = "2_waitGroup2",
    srcs = ["2_waitGroup2.go"],
)
