go_binary(
    name = "udemy-0-1-vars",
    srcs = ["udemy-0-1-vars.go"],
)

go_binary(
    name = "udemy-0-2-scope",
    srcs = ["udemy-0-2-scope.go"],
)

go_binary(
    name = "udemy-0-3-blankIdentifier",
    srcs = ["udemy-0-3-blankIdentifier.go"],
)

go_binary(
    name = "udemy-0-4-anonymous_func",
    srcs = ["udemy-0-4-anonymous_func.go"],
)

go_binary(
    name = "udemy-0-5-mem-pointers",
    srcs = ["udemy-0-5-mem-pointers.go"],
)

go_binary(
    name = "udemy-0-6-conditions",
    srcs = ["udemy-0-6-conditions.go"],
)

go_binary(
    name = "udemy-1-0-forLoop",
    srcs = ["udemy-1-0-forLoop.go"],
)

go_binary(
    name = "udemy-1-1-conversions",
    srcs = ["udemy-1-1-conversions.go"],
)

go_binary(
    name = "udemy-1-2-case_switch",
    srcs = ["udemy-1-2-case_switch.go"],
)

go_binary(
    name = "udemy-1-3-if-elseif-else",
    srcs = ["udemy-1-3-if-elseif-else.go"],
)

go_binary(
    name = "udemy-1-4-exercise",
    srcs = ["udemy-1-4-exercise.go"],
)

go_binary(
    name = "udemy-2-0-func",
    srcs = ["udemy-2-0-func.go"],
)

go_binary(
    name = "udemy-2-1-func",
    srcs = ["udemy-2-1-func.go"],
)

go_binary(
    name = "udemy-2-10-excercises",
    srcs = ["udemy-2-10-excercises.go"],
)

go_binary(
    name = "udemy-2-11-excercises",
    srcs = ["udemy-2-11-excercises.go"],
)

go_binary(
    name = "udemy-2-2-callbacks",
    srcs = ["udemy-2-2-callbacks.go"],
)

go_binary(
    name = "udemy-2-3-1-closure",
    srcs = ["udemy-2-3-1-closure.go"],
)

go_binary(
    name = "udemy-2-3-callbacks",
    srcs = ["udemy-2-3-callbacks.go"],
)

go_binary(
    name = "udemy-2-4a-recursion",
    srcs = ["udemy-2-4a-recursion.go"],
)

go_binary(
    name = "udemy-2-4b-recursion",
    srcs = ["udemy-2-4b-recursion.go"],
)

go_binary(
    name = "udemy-2-5-deferring",
    srcs = ["udemy-2-5-deferring.go"],
)

go_binary(
    name = "udemy-2-6-1-pointer",
    srcs = ["udemy-2-6-1-pointer.go"],
)

go_binary(
    name = "udemy-2-6-2-pointer",
    srcs = ["udemy-2-6-2-pointer.go"],
)

go_binary(
    name = "udemy-2-6-passByValue",
    srcs = ["udemy-2-6-passByValue.go"],
)

go_binary(
    name = "udemy-2-7-passByValue",
    srcs = ["udemy-2-7-passByValue.go"],
)

go_binary(
    name = "udemy-2-8-boolean",
    srcs = ["udemy-2-8-boolean.go"],
)

go_binary(
    name = "udemy-2-9-excercises",
    srcs = ["udemy-2-9-excercises.go"],
)

go_binary(
    name = "udemy-3-0-arrays",
    srcs = ["udemy-3-0-arrays.go"],
)

go_binary(
    name = "udemy-3-1-arrays",
    srcs = ["udemy-3-1-arrays.go"],
)

go_binary(
    name = "udemy-3-2-slices",
    srcs = ["udemy-3-2-slices.go"],
)

go_binary(
    name = "udemy-3-3-slices",
    srcs = ["udemy-3-3-slices.go"],
)

go_binary(
    name = "udemy-3-4-maps",
    srcs = ["udemy-3-4-maps.go"],
)

go_binary(
    name = "udemy-3-5-maps",
    srcs = ["udemy-3-5-maps.go"],
)

go_binary(
    name = "udemy-3-6-blank_identifier",
    srcs = ["udemy-3-6-blank_identifier.go"],
)

go_binary(
    name = "udemy-3-6-maps",
    srcs = ["udemy-3-6-maps.go"],
)

go_binary(
    name = "udemy-3-7-hashtables",
    srcs = ["udemy-3-7-hashtables.go"],
)

go_binary(
    name = "udemy-3-8-hashtables",
    srcs = ["udemy-3-8-hashtables.go"],
)

go_binary(
    name = "udemy-3-9-0-hashtables",
    srcs = ["udemy-3-9-0-hashtables.go"],
)

go_binary(
    name = "udemy-3-9-2-hashtables",
    srcs = ["udemy-3-9-2-hashtables.go"],
)

go_binary(
    name = "udemy-3-9-3-hashtables",
    srcs = ["udemy-3-9-3-hashtables.go"],
)

go_binary(
    name = "udemy-3-9-4-hashtables",
    srcs = ["udemy-3-9-4-hashtables.go"],
)

go_binary(
    name = "udemy-3-9-5-hashtables",
    srcs = ["udemy-3-9-5-hashtables.go"],
)

go_binary(
    name = "udemy-3-9a-hashtables",
    srcs = ["udemy-3-9a-hashtables.go"],
)

go_binary(
    name = "udemy-3-9b-hashtables",
    srcs = ["udemy-3-9b-hashtables.go"],
)

go_binary(
    name = "udemy-3-9c-hashtables",
    srcs = ["udemy-3-9c-hashtables.go"],
)

go_binary(
    name = "udemy-4-0-structs",
    srcs = ["udemy-4-0-structs.go"],
)

go_binary(
    name = "udemy-4-1-structs-ooo",
    srcs = ["udemy-4-1-structs-ooo.go"],
)

go_binary(
    name = "udemy-4-2-structs-methods",
    srcs = ["udemy-4-2-structs-methods.go"],
)

go_binary(
    name = "udemy-4-3-structs-methods",
    srcs = ["udemy-4-3-structs-methods.go"],
)

go_binary(
    name = "udemy-4-4-structs-json",
    srcs = ["udemy-4-4-structs-json.go"],
)

go_binary(
    name = "udemy-4-5-structs-json-marshal",
    srcs = ["udemy-4-5-structs-json-marshal.go"],
)

go_binary(
    name = "udemy-4-6-structs-json-encoding",
    srcs = ["udemy-4-6-structs-json-encoding.go"],
)

go_binary(
    name = "udemy-5-0-interfaces",
    srcs = ["udemy-5-0-interfaces.go"],
)

go_binary(
    name = "udemy-5-1-interfaces-exercise",
    srcs = ["udemy-5-1-interfaces-exercise.go"],
)

go_binary(
    name = "udemy-5-2-interfaces-sortPackage",
    srcs = ["udemy-5-2-interfaces-sortPackage.go"],
)

go_binary(
    name = "udemy-5-4a-interfaces",
    srcs = ["udemy-5-4a-interfaces.go"],
)

go_binary(
    name = "udemy-5-4b-interfaces",
    srcs = ["udemy-5-4b-interfaces.go"],
)

go_binary(
    name = "udemy-5-4c-interfaces",
    srcs = ["udemy-5-4c-interfaces.go"],
)

go_binary(
    name = "udemy-5-5-interfaces-pointer_receiver_methods",
    srcs = ["udemy-5-5-interfaces-pointer_receiver_methods.go"],
)

go_binary(
    name = "udemy-5-6-interfaces-assertion",
    srcs = ["udemy-5-6-interfaces-assertion.go"],
)

go_binary(
    name = "udemy-6-0-goroutines-waitGroup",
    srcs = ["udemy-6-0-goroutines-waitGroup.go"],
)

go_binary(
    name = "udemy-6-1-goroutines-parallelism",
    srcs = ["udemy-6-1-goroutines-parallelism.go"],
)

go_binary(
    name = "udemy-6-1-goroutines-waitGroup",
    srcs = ["udemy-6-1-goroutines-waitGroup.go"],
)

go_binary(
    name = "udemy-6-2-goroutines-mutex",
    srcs = ["udemy-6-2-goroutines-mutex.go"],
)

go_binary(
    name = "udemy-6-3-goroutines-atomicity",
    srcs = ["udemy-6-3-goroutines-atomicity.go"],
)

go_binary(
    name = "udemy-6-4-channels",
    srcs = ["udemy-6-4-channels.go"],
)

go_binary(
    name = "udemy-6-5-channels",
    srcs = ["udemy-6-5-channels.go"],
)

go_binary(
    name = "udemy-6-6a-channels",
    srcs = ["udemy-6-6a-channels.go"],
)

go_binary(
    name = "udemy-6-6b-channels",
    srcs = ["udemy-6-6b-channels.go"],
)

go_binary(
    name = "udemy-6-6c-channels",
    srcs = ["udemy-6-6c-channels.go"],
)

go_binary(
    name = "udemy-6-6d-channels",
    srcs = ["udemy-6-6d-channels.go"],
)

go_binary(
    name = "udemy-6-6e-channels",
    srcs = ["udemy-6-6e-channels.go"],
)

go_binary(
    name = "udemy-6-6f-channels",
    srcs = ["udemy-6-6f-channels.go"],
)

go_binary(
    name = "udemy-6-6g-channels-challenges",
    srcs = ["udemy-6-6g-channels-challenges.go"],
)

go_binary(
    name = "udemy-6-7a-channels-pipelines",
    srcs = ["udemy-6-7a-channels-pipelines.go"],
)

go_binary(
    name = "udemy-6-7b-channels-pipelines",
    srcs = ["udemy-6-7b-channels-pipelines.go"],
)

go_binary(
    name = "udemy-6-7c-channels-pipelines-challenge",
    srcs = ["udemy-6-7c-channels-pipelines-challenge.go"],
)

go_binary(
    name = "udemy-6-8-channels-pipelines-fanout-boring",
    srcs = ["udemy-6-8-channels-pipelines-fanout-boring.go"],
)

go_binary(
    name = "udemy-6-9-channels-pipelines-factorial-fanout",
    srcs = ["udemy-6-9-channels-pipelines-factorial-fanout.go"],
)

go_binary(
    name = "udemy-7-0-error-handling",
    srcs = ["udemy-7-0-error-handling.go"],
)

go_binary(
    name = "udemy-7-1-error-handling",
    srcs = ["udemy-7-1-error-handling.go"],
)

go_binary(
    name = "udemy-7-2-error-handling-recover",
    srcs = ["udemy-7-2-error-handling-recover.go"],
)
