// Code generated by protoc-gen-go.
// source: ship.proto
// DO NOT EDIT!

package protobuffer

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Ship struct {
	ShipName         *string            `protobuf:"bytes,1,req" json:"ShipName,omitempty"`
	CaptainName      *string            `protobuf:"bytes,2,req" json:"CaptainName,omitempty"`
	Crew             []*Ship_CrewMember `protobuf:"bytes,3,rep" json:"Crew,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Ship) Reset()         { *m = Ship{} }
func (m *Ship) String() string { return proto.CompactTextString(m) }
func (*Ship) ProtoMessage()    {}

func (m *Ship) GetShipName() string {
	if m != nil && m.ShipName != nil {
		return *m.ShipName
	}
	return ""
}

func (m *Ship) GetCaptainName() string {
	if m != nil && m.CaptainName != nil {
		return *m.CaptainName
	}
	return ""
}

func (m *Ship) GetCrew() []*Ship_CrewMember {
	if m != nil {
		return m.Crew
	}
	return nil
}

type Ship_CrewMember struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	SecClearance     *int32  `protobuf:"varint,3,req,name=secClearance" json:"secClearance,omitempty"`
	Position         *string `protobuf:"bytes,4,req,name=position" json:"position,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Ship_CrewMember) Reset()         { *m = Ship_CrewMember{} }
func (m *Ship_CrewMember) String() string { return proto.CompactTextString(m) }
func (*Ship_CrewMember) ProtoMessage()    {}

func (m *Ship_CrewMember) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Ship_CrewMember) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Ship_CrewMember) GetSecClearance() int32 {
	if m != nil && m.SecClearance != nil {
		return *m.SecClearance
	}
	return 0
}

func (m *Ship_CrewMember) GetPosition() string {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return ""
}

func init() {
}
