#!/usr/bin/env python
# encoding: utf-8

eggcolor = "green"
meat = "ham"
print eggcolor, "eggs and", meat

def breakfast():
  global eggcolor
  eggcolor = "red"
  meat = "bacon"
  print eggcolor, "eggs and", meat

breakfast()

print eggcolor, "eggs and", meat

