go_binary(
    name = "factoryPattern",
    srcs = ["factoryPattern.go"],
)

go_binary(
    name = "singletonPattern",
    srcs = ["singletonPattern.go"],
)

go_binary(
    name = "builderPattern",
    srcs = ["builderPattern.go"],
)

go_binary(
    name = "factorySituations",
    srcs = ["factorySituations.go"],
)
